Array
(
    [AVS] => 
    [Authorization_Num] => ET130682
    [Bank_Message] => Approved
    [Bank_Resp_Code] => 100
    [Bank_Resp_Code_2] => 
    [CAVV_Algorithm] => 0
    [CAVV_Response] => 
    [CVD_Presence_Ind] => 0
    [CVV2] => I
    [CardHoldersName] => Evelio Velez Jr.
    [Card_Number] => ###########3005
    [Client_Email] => 
    [Client_IP] => 68.194.208.52
    [Customer_Ref] => 
    [DollarAmount] => 46.47
    [EXact_Message] => Transaction Normal
    [EXact_Resp_Code] => 00
    [Ecommerce_Flag] => 
    [Expiry_Date] => 1121
    [Language] => 0
    [Reference_3] => 
    [Reference_No] => 
    [Retrieval_Ref_No] => 0413839
    [Secure_AuthRequired] => 0
    [Secure_AuthResult] => 0
    [SequenceNo] => 000004
    [SurchargeAmount] => 0
    [Tax1Amount] => 
    [Tax1Number] => 
    [Tax2Amount] => 
    [Tax2Number] => 
    [TransactionCardType] => AMERICAN EXPRESS
    [Transaction_Approved] => YES
    [Transaction_Error] => false
    [Transaction_Tag] => 2237537297
    [Transaction_Type] => 00
    [XID] => 
    [ZipCode] => 
    [exact_wsp_version] => 1.7
    [x_address] => 
    [x_amount] => 46.47
    [x_fee_amount] => 
    [x_auth_code] => ET130682
    [x_avs_code] => 
    [x_cavv_response] => 
    [x_city] => 
    [x_company] => 
    [x_country] => 
    [x_cust_id] => 
    [x_cvv2_resp_code] => I
    [x_description] => 
    [x_duty] => 
    [x_email] => 
    [x_fax] => 
    [x_first_name] => 
    [x_freight] => 
    [x_invoice_num] => 
    [x_last_name] => 
    [x_method] => 
    [x_phone] => 
    [x_po_num] => 
    [x_reference_3] => 
    [x_response_code] => 1
    [x_response_reason_code] => 1
    [x_response_reason_text] => Transaction has been approved
    [x_response_subcode] => S
    [x_ship_to_address] => 
    [x_ship_to_city] => 
    [x_ship_to_company] => 
    [x_ship_to_country] => 
    [x_ship_to_first_name] => 
    [x_ship_to_last_name] => 
    [x_ship_to_state] => 
    [x_ship_to_zip] => 
    [x_state] => 
    [x_tax] => 
    [x_tax_exempt] => 
    [x_trans_id] => 2237537297
    [x_type] => 
    [x_zip] => 
    [x_MD5_Hash] => 6b90ba61dfc5b72791c4f828de211402
    [timezone] => America/New_York
    [ci_session] => bea5dedd5f6751204737ada937627e19d70d7331
)